site_name: Pre-U Robotic Workshop
theme:
  name: material
  icon: 
    logo: material/robot-excited
  favicon: img/favicon.svg
  features:
    - toc.follow
    - toc.integrate
    - navigation.expand
    - content.code.annotate
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
site_dir: docs
docs_dir: src
extra_css:
  - css/main.css
  - css/reveal.css
  - css/reveal-themes/solarized.css
extra_javascript:
  - js/reveal.js
  - js/plugin/markdown/markdown.js
  - js/init-reveal.js
plugins: [ ]
extra:
  social: 
    - icon: fontawesome/solid/building
      link: https://university.sunway.edu.my/site
      name: School of Engineering and Technology
    - icon: fontawesome/brands/github
      link: https://ricwtk.github.io/
      name: Richard Wong
copyright: Prepared by <a href="https://ricwtk.github.io/" target="_blank">Richard Wong</a> for <a href="https://university.sunway.edu.my/set" taget="_blank">Sunway University, School of Engineering and Technology</a>
nav:
  - index.md
  - Basics: "basics.md"
  - Tutorial 1 LED: "tutorial1.md"
  - Tutorial 2 Motor: "tutorial2.md"
  - Tutorial 3 Ultrasonic sensor: "tutorial3.md"
  - Tutorial 4 Infrared sensors: "tutorial4.md"
  - Tutorial 5 LED matrix: "tutorial5.md"
  - Challenge 1: "challenge1.md"
  - Challenge 2: "challenge2.md"
  - Challenge 3: "challenge3.md"